
@local = http://localhost:3000
@render = replace!



// - - - - - - - - - - - - - - - - - - - - - LOCAL HOST

### list all Resources
{{local}}/resources

### list resource by id
{{local}}/resources/63c7a54289285a3f4521e2a8


### Create resource
POST {{local}}/resources HTTP/1.1
content-type: application/json

{"level_name":"Test namedsdgf","level_author":"kyle","level_block_data":[{"grid_x": "10","grid_y": "6","width": "1","height": "1","color": "green","bouncy": "true","causes_damage": "true"}]}


### Update resource
PUT {{local}}/resources/63c8edb0a3dec2188e7917bb HTTP/1.1 
content-type: application/json

{"level_name":"test level","level_author":"lyle","level_block_data":[{"grid_x": "11","grid_y": "6","width": "1","height": "1","color": "blue","bouncy": "true","causes_damage": "true"}]}


### Delete resource by Id
DELETE {{local}}/resources/63c89e0abcb8928b4d3569cf HTTP/1.1



// - - - - - - - - - - - - - - - - - - - - - RENDER

### list all resources
{{render}}/resources


### list resource by id
{{render}}/resources/63c8ede7136edea12ff5a9f8


### Create resource
POST {{render}}/resources HTTP/1.1
content-type: application/json

{"level_name":"render test level","level_author":"kyle","level_block_data":[{"grid_x": "10","grid_y": "6","width": "1","height": "1","color": "blue","bouncy": "true","causes_damage": "true"}]}


### Update resource
PUT {{render}}/resources/63c8ede7136edea12ff5a9f8 HTTP/1.1 
content-type: application/json

{"level_name":"render test level 1.0","level_author":"lyle","level_block_data":[{"grid_x": "10","grid_y": "6","width": "1","height": "1","color": "red","bouncy": "true","causes_damage": "true"}]}


### Delete resource by Id
DELETE {{render}}/resources/63c8ede7136edea12ff5a9f8 HTTP/1.1
