
@local = http://localhost:3000
@render = replace!



// - - - - - - - - - - - - - - - - - - - - - LOCAL HOST

### list all Resources
{{local}}/resources

### list resource by id
{{local}}/resources/63d2536bf5f39b559770438f


### Create resource
POST {{local}}/resources HTTP/1.1
content-type: application/json

{"title": "Test","subject": "Test","description":"Test","likes": "0","date_created": "1/26/2023","last_modified": "1/26/2023","lesson_numbers": [1],"links": [],"search_tags": [],"contributing_students": [],"featured_technologies": []}


### Update resource
PUT {{local}}/resources/63d2536bf5f39b559770438f HTTP/1.1 
content-type: application/json

{"title": "Test 1.0","subject": "Test","description": "Test","likes": "0","date_created": "1/26/2023","last_modified": "1/26/2023","lesson_numbers": [1],"links": [],"search_tags": [],"contributing_students": [],"featured_technologies": []}


### Delete resource by Id
DELETE {{local}}/resources/63d2536bf5f39b559770438f HTTP/1.1



// - - - - - - - - - - - - - - - - - - - - - RENDER

### list all resources
{{render}}/resources


### list resource by id
{{render}}/resources/63c8ede7136edea12ff5a9f8


### Create resource
POST {{render}}/resources HTTP/1.1
content-type: application/json

{"title": "Render Test","subject": "Test","description": "Test","likes": "0","date_created": "1/26/2023","last_modified": "1/26/2023","lesson_numbers": [1],"links": [],"search_tags": [],"contributing_students": [],"featured_technologies": []}


### Update resource
PUT {{render}}/resources/63c8ede7136edea12ff5a9f8 HTTP/1.1 
content-type: application/json

{"title": "Render Test 1.0","subject": "Test","description": "Test","likes": "0","date_created": "1/26/2023","last_modified": "1/26/2023","lesson_numbers": [1],"links": [],"search_tags": [],"contributing_students": [],"featured_technologies": []}

### Delete resource by Id
DELETE {{render}}/resources/63c8ede7136edea12ff5a9f8 HTTP/1.1
