
@local = http://localhost:3000
@render = https://cse341-rsrc-api.onrender.com



// - - - - - - - - - - - - - - - - - - - - - LOCAL HOST

### list all Users
{{local}}/users

### list user by id
{{local}}/users/63d35dd1d04d4248a6be8bff


### Create user
POST {{local}}/users HTTP/1.1
content-type: application/json

{"profile_id": "google-oauth2|1111111111111111111111","name": "Test User"}


### Update user
PUT {{local}}/users/63d35dd1d04d4248a6be8bff HTTP/1.1 
content-type: application/json

{"profile_id": "google-oauth2|1111111111111111111111","name": "Test User"}

### Delete user by Id
DELETE {{local}}/users/63d35dd1d04d4248a6be8bff HTTP/1.1

// - - - - - - - - - - - - - - - - - - - - - RENDER

### list all Users
{{render}}/users

### list user by id
{{render}}/users/63d35dd1d04d4248a6be8bff


### Create user
POST {{render}}/users HTTP/1.1
content-type: application/json

{"profile_id": "google-oauth2|1111111111111111111111","name": "Test User"}


### Update user
PUT {{render}}/users/63d35dd1d04d4248a6be8bff HTTP/1.1 
content-type: application/json

{"profile_id": "google-oauth2|1111111111111111111111","name": "Test User"}

### Delete user by Id
DELETE {{render}}/users/63d35dd1d04d4248a6be8bff HTTP/1.1